apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviedb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviedb
  template:
    metadata:
      labels:
        app: moviedb
    spec:
      containers:
        - name: moviedb
          image: vladpaliychuk/postgres:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "MovieDatabase"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: movie-db-secret
                  key: db_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: movie-db-secret
                  key: db_password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: pgdata-volume
              mountPath: /var/lib/postgresql/data/pgdata
      volumes:
        - name: pgdata-volume
          persistentVolumeClaim:
            claimName: pgdata-pvc
