# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  movie.api:
    build:
      context: "/home/slim/RiderProjects/ReelRate"
      dockerfile: "Movie/Movie.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Movie.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalogapi:dev"
    ports: []
    volumes:
    - "/home/slim/RiderProjects/ReelRate/Movie/Movie.API:/app:rw"
    - "/home/slim/RiderProjects/ReelRate:/src:rw"
    - "/home/slim/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
