# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  movie.api:
    build:
      context: "C:\\Users\\Vladyslav\\RiderProjects\\ReelRate"
      dockerfile: "Movie/Movie.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Movie.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "movie.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\Vladyslav\\RiderProjects\\ReelRate\\Movie\\Movie.API:/app:rw"
    - "C:\\Users\\Vladyslav\\RiderProjects\\ReelRate:/src:rw"
    - "C:\\Users\\Vladyslav\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
